# Generated by Django 2.0.4 on 2018-04-06 21:14

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Album'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=70),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums'),
        ),
    ]
